#!/bin/bash

#############################
## Zona de auto debugging ##
#[+][+][+][+][+][+][+][+][+][+][+][+]#
handleError() {
    echo -e "\033[1;31m[+]\e[0m\e[0;36m==================================================\e[0m\033[1;31m[+]\e[0m"
    echo -e "\033[1;31m[+]\e[0m [ERROR]=> LINEA $1; Script error $0"
    echo -e "\033[1;31m[+]\e[0m [Codigo error $2 ]"
    echo -e "\033[1;31m[+]\e[0m\e[0;36m==================================================\e[0m\033[1;31m[+]\e[0m"
    exit 1
}
trap 'handleError $LINENO $?' ERR
#[+][+][+][+][+][+][+][+][+][+][+][+]#

function main() { clear

    # Crea una copia de seguridad de Shadow
    echo -e "\n\n[ \033[1;93m Respaldo de Shadow en camino...\033[0m ]"
    sleep 1.5s
    sudo rsync -rav /etc/shadow ~/VIAUYServer/Container/SaveData_"$(date +%d-%m-%Y)"/ && echo -e "\n\n[ \033[1;32m Respaldo completado... \033[0m ]" || echo -e "\n\n[ \033[4;91mOcurrio un problema...\033[0m ]" 

    # Crea una copia de seguridad de Passw
    echo -e "\n\n[ \033[1;93m Respaldo de Passwd en camino... \033[0m ]"
    sleep 1.5s
    sudo rsync -rav /etc/passwd ~/VIAUYServer/Container/SaveData_"$(date +%d-%m-%Y)"/ && echo -e "\n\n[ \033[1;32m Respaldo completado... \033[0m ]" || echo -e "\n\n[ \033[4;91mOcurrio un problema...\033[0m ]" 
        
    # Crea una copia de seguridad de Group
    echo -e "\n\n[ \033[1;93m Respaldo de Group en camino... \033[0m ]"
    sleep 1.5s
    sudo rsync -rav /etc/group ~/VIAUYServer/Container/SaveData_"$(date +%d-%m-%Y)"/ && echo -e "\n\n[ \033[1;32m Respaldo completado... \033[0m ]" || echo -e "\n\n[ \033[4;91mOcurrio un problema...\033[0m ]" 
    read -n1 -p "Presione cualquier tecla para [ VOLVER ]..."
    ( exec "./main.sh" )
}

main
    
