#!/bin/bash
#############################
## Zona de auto debugging ##
#[+][+][+][+][+][+][+][+][+][+][+][+]#
handleError() {
    echo -e "\033[1;31m[+]\e[0m\e[0;36m============================================\e[0m\033[1;31m[+]\e[0m"
    echo -e "\033[1;31m[+]\e[0m [ERROR]=> LINEA $1; Script error $0 \033[1;31m[+]\e[0m"
    echo -e "\033[1;31m[+]\e[0m [Codigo error $2 ]                        \033[1;31m[+]\e[0m"
    echo -e "\033[1;31m[+]\e[0m\e[0;36m============================================\e[0m\033[1;31m[+]\e[0m"
    exit 1
}
trap 'handleError $LINENO $?' ERR
trap "echo [x] Que forma mas arcaica de salir, se implementaron funciones modernas para ello [x]; exit" SIGINT
#[+][+][+][+][+][+][+][+][+][+][+][+]#


########################
## ELIMINAR USUARIOS ##
######################
function delUser() { clear
    ##### Declaracion de variables a utilizar
    declare -i usDel
    #####

    echo -e "\n\e[0;36m[x]===============================================[x]\e[0m"
    echo -e "\e[0;36m[x]\e[0m  ¿Desea eliminar definitivamente un usuario?  \e[0;36m[x]\e[0m"
    echo -e "\e[0;36m[x]===============================================[x]\e[0m"
    read -r -p "[Yy] / [Nn] => " op
    sleep 0.45s
    clear

    if [[ "$op" =~ [Yy] ]]; then
        echo -e "\n\e[0;36m[x]==================================[x]\e[0m"
        echo -e "\e[0;36m[x]\e[0m         \033[1;91m\033[5m\033[3mEliminar Usuario\033[0m         \e[0;36m[x]\e[0m"
        echo -e "\e[0;36m[x]==================================[x]\e[0m"
        read -r -p "$(echo -e "\e[0;33m\033[1m[+]\e[0m") Nombre de usuario => " del
        usDel=$(cat /etc/passwd | grep -c -w -i "$del" | cut -d ":" -f1)

        if [ "$usDel" -eq 0 ]; then
            sudo userdel -r -f "$del"
            echo -e "\e[0;36m[+]\e[0m Se ha eliminado \033[46mexitosamente\033[0m el usuario ""$del"" \e[0;36m[+]\e[0m"
            read -n1 -p -r "Presione cualquier tecla para [ CONTINUAR ]..."
            ( exec "./main.sh" ) && clear
        else
            clear
            echo
            echo -e "\033[4;35mNo es una opcion lo que intentas\e[0m"
            echo
            sleep 2s
            ( exec "./test.sh" ) && clear
        fi
        
    elif [[ $op =~ [Nn] ]]; then
        echo -e "\e[0;36m[+]\e[0m Se ha \033[46mdenegado exitosamente\033[0m la eliminacion \e[0;36m[+]\e[0m"
        read -n1 -p -r "Presione cualquier tecla para [ CONTINUAR ]..."
        ( exec "./main.sh" ) && clear
    fi
}
delUser